CREATE TABLE COUNTRY (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(250) UNIQUE, capital VARCHAR(250) UNIQUE);
INSERT INTO COUNTRY VALUES (1, 'India', 'Delhi');
INSERT INTO COUNTRY VALUES (2, 'Japan', 'Tokyo');
INSERT INTO COUNTRY VALUES (3, 'France', 'Paris');
INSERT INTO COUNTRY VALUES (4, 'Germany', 'Berlin');